type Comet @entity(immutable: true) {
  id: Bytes! # address
  configController: Bytes!

  updatedAt: BigInt!
  createdAt: BigInt!
}

type User @entity(immutable: false) {
  id: Bytes! # address
  principal: BigInt!
  userAddress: Bytes!
  proxyCometAddress: Bytes!

  updatedAt: BigInt!
  createdAt: BigInt!
}

type WhitelistedCollateral @entity(immutable: true) {
  id: Bytes! # address
  priceFeed: Bytes! # address
  decimals: BigInt!
  maxBorrowCollateralFactor: BigInt!
  minBorrowCollateralFactor: BigInt!
  maxLiquidateCollateralFactor: BigInt!
  minLiquidateCollateralFactor: BigInt!
  maxLiquidationFactor: BigInt!
  minLiquidationFactor: BigInt!

  createdAt: BigInt!
}

type BaseAssetCurve @entity(immutable: true) {
  id: String!
  supplyKink: BigInt!
  supplyPerYearInterestRateBase: BigInt!
  supplyPerYearInterestRateSlopeLow: BigInt!
  supplyPerYearInterestRateSlopeHigh: BigInt!
  borrowKink: BigInt!
  borrowPerYearInterestRateBase: BigInt!
  borrowPerYearInterestRateSlopeLow: BigInt!
  borrowPerYearInterestRateSlopeHigh: BigInt!

  createdAt: BigInt!
}
type WhitelistedBase @entity(immutable: false) {
  id: Bytes! # address
  priceFeed: Bytes! # address
  decimals: BigInt!

  curve: BaseAssetCurve!

  minBorrow: BigInt!

  updatedAt: BigInt!
  createdAt: BigInt!
}


type ConfigController @entity(immutable: false) {
  id: Bytes! # address
  owner: Bytes! # address
  guardian: Bytes! # address
  sandboxController: Bytes! # address
  marketFactory: Bytes! # address

  curatorFee: BigInt!
  name: String!
  curatorProposalDuration: BigInt!
  proposalDuration: BigInt!

  updatedAt: BigInt!
  createdAt: BigInt!
}

type BaseConfiguration @entity(immutable: false) {
  id: Bytes! # ConfigController address

  comet: Comet!
  curve: BaseAssetCurve!

  updatedAt: BigInt!
  createdAt: BigInt!
}

type CollateralConfiguration @entity(immutable: false) {
  id: Bytes! # asset address

  priceFeed: Bytes!
  decimals: BigInt!
  borrowCollateralFactor: BigInt!
  liquidateCollateralFactor: BigInt!
  liquidationFactor: BigInt!
  supplyCap: BigInt!

  updatedAt: BigInt!
  createdAt: BigInt!
}
